# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

import "Actions/custom_actions"

fastlane_version "2.108.0"

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
    puts "custom_lane"
  end
  lane :bm_build do
    puts "bm_build"
  end
  lane :bm_appstore do
    puts "bm_appstore"
  end
  lane :bm_enterprise do
    puts "bm_enterprise"
  end
  lane :bm_development do
    # sigh(force: true)
    gym(
      workspace: "ToDoList.xcworkspace",
      scheme: "ToDoList",
      silent: true,
      clean: true,
      output_directory: "build", # Destination directory. Defaults to current directory.
      output_name: "待办事项.ipa", # specify the name of the .ipa file to generate (including file extension)
      export_method: "ad-hoc", # app-store, ad-hoc, package, enterprise, development, developer-id
      include_bitcode: false,
      # export_xcargs: "-allowProvisioningUpdates"
    )
  end
  lane :bm_test do
    
  end
end
