# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ToDoList' do

    pod 'Masonry', '1.1.0'
    pod 'AFNetworking', '3.2.1'

  target 'ToDoListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ToDoListUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
