platform :ios, '9.0'

target 'BWToDoList' do

  pod 'Masonry', '1.1.0'
  pod 'SDWebImage', '4.2.3'
  pod 'YTKNetwork', '2.0.4'
  pod 'MLeaksFinder', '1.0.0'

#  target 'BWToDoListTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
#  target 'BWToDoListUITests' do
#    inherit! :search_paths
#    # Pods for testing
#  end

end
