platform :ios, '9.0'

target 'BWToDoListSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 4.0.0'
  pod 'Alamofire', '~> 4.7.2'
  pod 'SDWebImage', '~> 4.3.3'

  target 'BWToDoListSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BWToDoListSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
